# Generated by Django 4.0.3 on 2023-04-13 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hotel', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotel',
            name='check_in_range',
        ),
        migrations.RemoveField(
            model_name='hotel',
            name='check_out_range',
        ),
        migrations.AddField(
            model_name='room',
            name='check_in_range',
            field=models.DateField(default='2023-04-18'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='room',
            name='check_out_range',
            field=models.DateField(default='2023-04-18'),
            preserve_default=False,
        ),
    ]
