# Generated by Django 4.0.3 on 2023-04-13 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hotel', '0002_remove_hotel_check_in_range_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='is_reserved',
            field=models.BooleanField(default=False),
        ),
    ]
